hmcts/expressjs-template

- src/main/app.ts
* add missing configuration bits (microservice, team, evironment)
* setup the application to log HTTP requests
```
[ ] Yes
[x] No
```
> RPE-30: extend logging setup

- .dockerignore
- Dockerfile
- README.md
- docker-compose.yml
- src/main/app.ts
Make it possible to run the application in Docker.
```
[ ] Yes
[x] No
```
> RPE-30: add Docker setup

- README.md
- config/default.json
- package.json
- src/main/app.ts
- src/main/views/macros/csrf.njk
- yarn.lock
Setup CSRF prevention at application level
```
[ ] Yes
[x] No
```
> RPE-30: setup CSRF prevention

- README.md
- config/default.json
- package.json
- src/main/app.ts
- src/main/modules/helmet/index.ts
Setup helmet to add various security-related HTTP headers to application's responses
```
[ ] Yes
[x] No
```
> RPE-30: secure the application with helmet

- README.md
- package.json
- src/main/routes/health.ts
- yarn.lock
Create a basic version of health endpoint.
Also, made tiny updated in README.md
```
[ ] Yes
[x] No
```
> Create a health endpoint

- src/main/app.ts
- src/main/views/error.njk
- src/main/views/home.njk
- src/main/views/not-found.njk
Return 'Not found' page for requests to undefined paths
```
[ ] Yes
[x] No
```
> Return 'Not found' page for requests to undefined paths

- .travis.yml
- README.md
- package.json
- src/main/views/home.njk
- src/test/a11y/a11y.ts
- yarn.lock
Setup accessibility testing with pa11y
```
[ ] Yes
[x] No
```
> Setup accessibility testing with pa11y

- src/main/app.ts
Log HTTP request processing errors
```
[ ] Yes
[x] No
```
> RPE-30: log request processing errors

- package.json
- yarn.lock
Add common dependencies related with unit testing and security.
Also, moved mocha dependencies to devDependencies
```
[ ] Yes
[x] No
```
> Add common dependencies related to unit testing and security

- Jenkinsfile_CNP.disabled
- Jenkinsfile_nightly
- charts/rpe-expressjs-template/.helmignore
- charts/rpe-expressjs-template/Chart.yaml
- charts/rpe-expressjs-template/requirements.yaml
- charts/rpe-expressjs-template/templates/NOTES.txt
- charts/rpe-expressjs-template/values.aat.template.yaml
- charts/rpe-expressjs-template/values.preview.template.yaml
- charts/rpe-expressjs-template/values.yaml
> Adding charts and Jenkins files

- src/main/routes/health.ts
> Adding liveness

- package.json
- yarn.lock
> Removing deprecated nsp

- README.md
- config/default.json
> Removing hpkp references

- .gitignore
- package.json
- src/main/app.ts
- src/main/views/template.njk
- src/main/views/webpack/css.njk
- src/main/views/webpack/js.njk
- src/main/webpack/htmlWebpack.js
- src/main/webpack/scss.js
- webpack.config.js
- yarn.lock
> Adding webpack hashing 

- Jenkinsfile_CNP.disabled
- bin/init.sh
Update generated CNP File
```
[ ] Yes
[ x] No
```
> Update CNP File

- .github/renovate.json
- charts/rpe-expressjs-template/Chart.yaml
- charts/rpe-expressjs-template/requirements.yaml
- package.json
- yarn.lock
> Bump base chart and renovate 

- package.json
- yarn.lock
Add the minimum required configuration to build the project on Jenkins successfully
> Add Jenkins pipeline configuration

- renovate.json
We want to use: https://github.com/hmcts/expressjs-template/blob/master/.github/renovate.json
> Remove duplicate renovate.json

- .gitignore
- package.json
- src/main/development.ts
- src/main/views/webpack/css-template.njk
- src/main/views/webpack/css.njk
- src/main/views/webpack/js-template.njk
- src/main/views/webpack/js.njk
- webpack.config.js
- webpack/htmlWebpack.js
- webpack/scss.js
- yarn.lock
> Fix webpack

- sonar-project.properties
N/A
Fix sonar coverage report path property
```
[ ] Yes
[X] No
```
> Fix sonar coverage report path property

- jest.a11y.config.js
- jest.config.js
- jest.routes.config.js
Fixes https://github.com/hmcts/expressjs-template/issues/393
> Remove duplicate module file extension

- .github/dependabot.yml
- .github/renovate.json
https://tools.hmcts.net/jira/browse/DTSPO-6459
```
[ ] Yes
[x] No
```
> Remove dependabot + extend renovate

- Jenkinsfile_CNP.disabled
It doesn't work right with zero-installs so needs rebuilding
> DTSPO-6464 Rebuild puppeteer on pipeline

- .github/codeql/codeql-config.yml
- .github/workflows/codeql.yaml
Tested in a fork and I've suppressed the false positive
> Enable CodeQL scanning (#534

- package.json
Just upping this value to v18
```
[ ] Yes
[x] No
```
> DTSPO-10334 - set node engine to minimum of v18

- .github/renovate.json
Getting quite a few PRs with conflicts that can't be fixed in the GH Gui, to save some time I'm wondering if it would be better to close the PRs and to get renovate to recreate
```
[ ] Yes
[ ] No
```
> Recreate closed PRs
